const data = {
	results: [
		{
			id: 1,
			display: "chicken noodle soup",
			search_value: "chicken noodle soup",
			type: "ingredient",
			time: 20,
			image: "https://picsum.photos/id/235/400",
		},
		{
			id: 2,
			display: "chicken soup",
			search_value: "chicken soup",
			type: "ingredient",
			time: 10,
			image: "https://picsum.photos/id/222/400",
		},
		{
			id: 3,
			display: "chicken cocktail",
			search_value: "chicken noodle soup",
			type: "ingredient",
			time: 17,
			image: "https://picsum.photos/id/353/400",
		},
		{
			id: 4,
			display: "chicken parmesano risota",
			search_value: "chicken soup",
			type: "ingredient",
			time: 31,
			image: "https://picsum.photos/id/323/400",
		},
		{
			id: 5,
			display: "rosted chicken",
			search_value: "chicken noodle soup",
			type: "ingredient",
			time: 45,
			image: "https://picsum.photos/id/287/400",
		},
		{
			id: 6,
			display: "whole chicken with corn",
			search_value: "chicken soup",
			type: "ingredient",
			time: 15,
			image: "https://picsum.photos/id/258/400",
		},
		{
			id: 7,
			display: "chicken italiano",
			search_value: "chicken noodle soup",
			type: "ingredient",
			time: 40,
			image: "https://picsum.photos/id/341/400",
		},
		{
			id: 8,
			display: "fried chicken noodles",
			search_value: "chicken soup",
			type: "ingredient",
			time: 60,
			image: "https://picsum.photos/id/311/400",
		},
		{
			id: 9,
			display: "chicken fingers",
			search_value: "chicken noodle soup",
			type: "ingredient",
			time: 35,
			image: "https://picsum.photos/id/319/400",
		},
		{
			id: 10,
			display: "slow roasted chicken bresats",
			search_value: "chicken soup",
			type: "ingredient",
			time: 120,
			image: "https://picsum.photos/id/291/400",
		},
	],
};

export default data;
